FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm prune --omit=dev


FROM node:22-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY --from=build /app .

EXPOSE 5000

CMD ["node", "server.js"]
