FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

COPY . .

RUN npm install --omit=dev


FROM node:22-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY --from=build /app .

USER node

EXPOSE 5000

CMD ["node", "server.js"]
