name: application pipeline

on:
  push:
    branches: 
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: install dependencies
        run: cd app/backend && npm ci
      - name: launch tests
        run: cd app/backend && npm test
        env:
          STRIPE_SECRET_KEY: "sk_test_mockup"
          JWT_SECRET: "sk_test_jwt"

  scan-secrets-leaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: run gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    
  build-and-secure:
      runs-on: ubuntu-latest
      needs: [run-tests, scan-secrets-leaks]
      strategy:
        fail-fast: false
        matrix: 
          include: 
            - composant: backend 
              path: ./app/backend
            - composant: frontend
              path: ./app/frontend
            - composant: nginx
              path: ./nginx
      steps:
        - uses: actions/checkout@v4
        - name: build images
          run: |
            docker build -t app/${{ matrix.composant }}:latest ${{ matrix.path }}
        - name: scan images
          uses: aquasecurity/trivy-action@v0.36.0
          with: 
            image-ref: 'app/${{ matrix.composant }}:latest'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            severity: 'HIGH,CRITICAL'
